apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restart-dba-bot-db
  namespace: dba-bot
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    resourceNames: ["dba-bot-db"]
    verbs: ["get", "patch"]
