apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restart-dba-bot-db
  namespace: dba-bot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: restart-dba-bot-db
subjects:
  - kind: ServiceAccount
    name: restart-dba-bot-db
    namespace: dba-bot